error: less error prone `error_kind!` macro
* serializable error kinds written with small `error_kind!` macro, which
  removes error-prone kind <-> code/name/msg mapping fns.

* all error kinds now use an `Unknown(_)` variant rather than just a
  fixed `Unknown = 0` variant so (1) we can preserve the underlying
  error code for better debugging and (2) intermediate proxies can avoid
  losing information.

* rename `CommonError` -> `RestClientError` to reflect usage.

* more accurately reflect reqwest error variants in `RestClientErrorKind`.

* now require that all error kind are a strict superset of the
  `RestClientErrorKind`s. This lets us stop retrying on rest client error
  kinds correctly, when requested.

* new approach lets us easily assert all error kind invariants in a test.