error: Don't display `[106=Command]` prefix
This didn't add any useful information beyond what was already available
in the kind_msg and the additional context, and looked ugly, so we're
removing.

-- Additional notes on the command error --

The old structure was:

```
[0=Unknown] Unknown error: Here's my extra info
[106=Command]: Here's my extra info
```

We wanted:

```
Unknown error: Here's my extra info
Here's my extra info
```

But naively removing the `[106=Command]` part results in:

```
Unknown error: Here's my extra info
: Here's my extra info
```

To make the structure work, I changed the command kind msg to just
"Error", so it's

```
Unknown error: Here's my extra info
Error: Here's my extra info
```

Which is still concise (even more concise than before) while respecting
the structure.

I also added the invariant that all kind msgs must be non-empty, and
shouldn't end with '.'.