error: Alphabetize macro invocations + impls
- No logic changes here, just moving things around.
- I also thought it made sense to have each `ToHttpStatus` impl right
  below the corresponding `api_error_kind!` invocation so (1) it's easy
  to remember to implement it and (2) one doesn't need to jump around or
  open splits to write the impl.