error: Don't serialize null data, sensitive: false
Elides these two fields which are usually not set so user-facing
`ErrorResponse` JSONs can be a bit shorter and nicer, e.g.

```
{"code":105,"msg":"Server is at capacity: Not enough memory to start
meganode for run request","data":null,"sensitive":false}
```

->

```
{"code":105,"msg":"Server is at capacity: Not enough memory to start
meganode for run request"}
```